### ISSUE TITLE
秘密鍵と公開鍵のページの修正

### ISSUE THREAD

**Issue by yuki-kimoto** [yuki-kimoto/perlzemiubuntu#1]
秘密鍵と公開鍵が逆。

sshのユーザー名とIPアドレスが逆。

**Comment by angel-p57** [comment]
* まず、SSHの秘密鍵を保存しておくディレクトリに移動します。  
 そのディレクトリは当初ないので、「無い場合は作成」となります。  
 ※ sshコマンドなどで勝手にできるので気付かない場合もある
 もし手順を紹介するなら「無い場合は mkdir、不適切なパーミッションだとトラブルの元なので -m でパーミッション 700 を指定するのが推奨」くらいでしょうか。

* 秘密鍵、あるいは、公開鍵のどちらかを「~/.ssh」ディレクトリに配置するだろう  
 原則として、秘密鍵・公開鍵はペアで使うので「どちらかを」は不自然です。

* パスフレーズとは、パスワードのことです。  
 認証に使う「パスワード」と、鍵を保護する「パスフレーズ」で折角用語が分かれているところ、混ぜてしまうと混乱の元です。  
 「鍵を保護する目的で秘密鍵ファイルに設定するもの」「ログイン用パスワードとは別」の明記がほしいです。

* リモートサーバーの公開鍵は、リモートサーバーの「~/.ssh/authorized_keys」に設定します。
  * 設定します  
    「登録します」の方が分かり易いでしょう
  * リモートサーバーの公開鍵は  
    登録するのは「接続元(クライアント側)の機器の公開鍵」です

* ssh-keygenで作成した公開鍵ファイルをそのまま設置しておくわけではない  
  別にそれでも使えるので、理由として合っていません。  
  「公開鍵ファイルをそのまま設置する手順に慣れると、既存の鍵情報を意図せず消すおそれがあり危険なため」くらいです

* その場合は、1行以上空けてください。  
  この記述だと空行を設けるようにも読めます。「行を変えて」か「1行1公開鍵となるように」でしょうか。

* パーミッションは600にします。  
  後で出てくる「秘密鍵のパーミッションは600である必要があります」と紛らわしいことに authorized_keys の 600 は「推奨」です。  
  ※細かいことを言うと、秘密鍵のパーミッションも 600 と決まってるわけではないけど、こっちは大した問題ではない

**Comment by shinshina-kimoto** [comment]
ありがとうございます。

質問なのですが

「.pub」の公開鍵は、そのまま配置しても動くのですね?

> 秘密鍵、あるいは、公開鍵のどちらかを「~/.ssh」ディレクトリに配置するだろう
> 原則として、秘密鍵・公開鍵はペアで使うので「どちらかを」は不自然です。

表現を考えてみます。

リモートに公開鍵を配置する場合は、ローカルに秘密鍵を。自分自身が接続される場合は、ローカルに公開鍵を、接続元に秘密鍵を置くという意味でした。

**Comment by yuki-kimoto** [comment]
ありがとうございます。

質問なのですが

「.pub」の公開鍵は、そのまま配置しても動くのですね?

> 秘密鍵、あるいは、公開鍵のどちらかを「~/.ssh」ディレクトリに配置するだろう
> 原則として、秘密鍵・公開鍵はペアで使うので「どちらかを」は不自然です。

表現を考えてみます。

リモートに公開鍵を配置する場合は、ローカルに秘密鍵を。自分自身が接続される場合は、ローカルに公開鍵を、接続元に秘密鍵を置くという意味でした。

そのほかの部分は、僕が勘違いしていたところでした。記事を修正してみます。


自分が公開鍵の専門家ではないことを追記して、

推奨される公開鍵やssh-keygenの解説が掲載されているサイトがあれば、そちらにリンクを張ることも可能です。自推、他推、は問いません。

**Comment by yuki-kimoto** [comment]
修正しました。

sshコマンド

https://linux.perlzemi.com/blog/20200621103220.html

ssh-keygen

https://ubuntu.perlzemi.com/blog/20200623095744.html

**Comment by angel-p57** [comment]
> 「.pub」の公開鍵は、そのまま配置しても動くのですね?

公開鍵ファイルをそのまま XXX.pub として置いても意味がないです。( 別のソフトだとそういうのもありますが )
しかし、「公開鍵を XXX.pub として保存(転送)する → authorized_keys に rename ( mv ) する」という手法はあります。ちょっと見たことある人ならこのことを想像することは考えられます。

> リモートに公開鍵を配置する場合は、ローカルに秘密鍵を。自分自身が接続される場合は、ローカルに公開鍵を、接続元に秘密鍵を置くという意味でした。

これも誤解されることが多いのですが、秘密鍵-公開鍵は完全な対立関係にあるものではありません。
sshクライアントは、秘密鍵・公開鍵を両方ペアで使うからです。
※公開鍵ファイルがなくても秘密鍵ファイルから公開鍵データを作り出すので問題が表面化しないことが多いですが、条件によっては、「ペアで使う」意識がないとトラブルの原因になります

また、authorized_keys も単なる公開鍵ファイルではなく、「複数の公開鍵を」「鍵毎の設定も込みで登録できる」鍵の登録簿です。

つまり、「ローカルに秘密鍵を置いてリモートに公開鍵を置く」というのは、上記実態にあまり合った表現にならないわけです。
※「ローカルで鍵ペアを持つ、リモートに公開鍵を登録する」になる。
※「登録する」という言葉を使っておけば、githubのように authorized_keys ファイルを使わないような形態でもそのまま表現できる ( どう登録するかの違いだけだから )

**Comment by yuki-kimoto** [comment]
sshクライアントは、秘密鍵・公開鍵を両方ペアで使うからです。

「ローカルで鍵ペアを持つ」

なるほど、公開鍵がなかった場合は、秘密鍵から公開鍵を生成しているだけで、SSHクライアントとしては、公開鍵と秘密鍵を両方使うというのが、本来のあり方なのですね。

もう一度、今回のコメントの内容が正しく伝わるように、書き直してみますね。

**Comment by yuki-kimoto** [comment]
@angel-p57

再修正を行いました。
